project/src/Entity/TaskStatus.php
<?php

namespace App\Entity;

use App\Repository\TaskStatusRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

use Gedmo\Mapping\Annotation as Gedmo;

/**
 * @ORM\Entity(repositoryClass=TaskStatusRepository::class)
 */
class TaskStatus
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="integer")
     */
    private $priority;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_active;

    /**
     * @ORM\OneToMany(targetEntity=Task::class, mappedBy="status")
     */
    private $tasks;

    /**
     * @ORM\Column(type="string", length=255)
     * @Gedmo\Slug(fields={"name"})
     */
    private $systemName;

    public function __construct()
    {
        $this->tasks = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getPriority(): ?int
    {
        return $this->priority;
    }

    public function setPriority(int $priority): self
    {
        $this->priority = $priority;

        return $this;
    }

    public function getIsActive(): ?bool
    {
        return $this->is_active;
    }

    public function setIsActive(bool $is_active): self
    {
        $this->is_active = $is_active;

        return $this;
    }

    /**
     * @return Collection|Task[]
     */
    public function getTasks(): Collection
    {
        return $this->tasks;
    }

    public function addTask(Task $task): self
    {
        if (!$this->tasks->contains($task)) {
            $this->tasks[] = $task;
            $task->setStatus($this);
        }

        return $this;
    }

    public function removeTask(Task $task): self
    {
        if ($this->tasks->contains($task)) {
            $this->tasks->removeElement($task);
            // set the owning side to null (unless already changed)
            if ($task->getStatus() === $this) {
                $task->setStatus(null);
            }
        }

        return $this;
    }

    public function getSystemName(): ?string
    {
        return $this->systemName;
    }

    public function setSystemName(string $systemName): self
    {
        $this->systemName = $systemName;

        return $this;
    }
}

project/src/Form/TaskStatusType.php
<?php

namespace App\Form;

use App\Entity\TaskStatus;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class TaskStatusType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
            ->add('priority')
            ->add('is_active')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => TaskStatus::class,
        ]);
    }
}

project/src/Controller/TaskStatusController.php
<?php

namespace App\Controller;

use App\Entity\TaskStatus;
use App\Form\TaskStatusType;
use App\Repository\TaskStatusRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;

/**
 * @Route("/task-status")
 * @IsGranted("ROLE_ADMIN")
 */
class TaskStatusController extends AbstractController
{
    /**
     * @Route("/", name="task_status_index", methods={"GET"})
     */
    public function index(TaskStatusRepository $taskStatusRepository): Response
    {
        return $this->render('task_status/index.html.twig', [
            'task_statuses' => $taskStatusRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="task_status_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $taskStatus = new TaskStatus();
        $form = $this->createForm(TaskStatusType::class, $taskStatus);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($taskStatus);
            $entityManager->flush();

            return $this->redirectToRoute('task_status_index');
        }

        return $this->render('task_status/new.html.twig', [
            'task_status' => $taskStatus,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="task_status_show", methods={"GET"})
     */
    public function show(TaskStatus $taskStatus): Response
    {
        return $this->render('task_status/show.html.twig', [
            'task_status' => $taskStatus,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="task_status_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, TaskStatus $taskStatus): Response
    {
        $form = $this->createForm(TaskStatusType::class, $taskStatus);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('task_status_index');
        }

        return $this->render('task_status/edit.html.twig', [
            'task_status' => $taskStatus,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="task_status_delete", methods={"DELETE"})
     */
    public function delete(Request $request, TaskStatus $taskStatus): Response
    {
        if ($this->isCsrfTokenValid('delete'.$taskStatus->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($taskStatus);
            $entityManager->flush();
        }

        return $this->redirectToRoute('task_status_index');
    }
}

project/templates/task_status/_delete_form.html.twig
<form method="post" action="{{ path('task_status_delete', {'id': task_status.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ task_status.id) }}">
    <button class="btn">Delete</button>
</form>

project/templates/task_status/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

project/templates/task_status/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit TaskStatus{% endblock %}

{% block body %}
    <h1>Edit TaskStatus</h1>

    {{ include('task_status/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('task_status_index') }}">back to list</a>

    {{ include('task_status/_delete_form.html.twig') }}
{% endblock %}

project/templates/task_status/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}TaskStatus index{% endblock %}

{% block body %}
    <h1>TaskStatus index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Priority</th>
                <th>Is_active</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for task_status in task_statuses %}
            <tr>
                <td>{{ task_status.id }}</td>
                <td>{{ task_status.name }}</td>
                <td>{{ task_status.priority }}</td>
                <td>{{ task_status.isActive ? 'Yes' : 'No' }}</td>
                <td>
                    <a href="{{ path('task_status_show', {'id': task_status.id}) }}">show</a>
                    <a href="{{ path('task_status_edit', {'id': task_status.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('task_status_new') }}">Create new</a>
{% endblock %}

project/templates/task_status/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New TaskStatus{% endblock %}

{% block body %}
    <h1>Create new TaskStatus</h1>

    {{ include('task_status/_form.html.twig') }}

    <a href="{{ path('task_status_index') }}">back to list</a>
{% endblock %}

project/templates/task_status/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}TaskStatus{% endblock %}

{% block body %}
    <h1>TaskStatus</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ task_status.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ task_status.name }}</td>
            </tr>
            <tr>
                <th>Priority</th>
                <td>{{ task_status.priority }}</td>
            </tr>
            <tr>
                <th>Is_active</th>
                <td>{{ task_status.isActive ? 'Yes' : 'No' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('task_status_index') }}">back to list</a>

    <a href="{{ path('task_status_edit', {'id': task_status.id}) }}">edit</a>

    {{ include('task_status/_delete_form.html.twig') }}
{% endblock %}